include: package:flutter_lints/flutter.yaml

# TODO [LB] flesh out
linter:
  rules:
    - always_declare_return_types
    - always_specify_types
    - always_use_package_imports
    - annotate_overrides
    - avoid_empty_else
    - avoid_relative_lib_imports
    - prefer_final_fields